#!/bin/zsh

fns="zsh/functions"
system_scriptpath="$HOME/.piggy/scripts"

mkdir -p "$HOME/.piggy"
mkdir -p "$system_scriptpath"

echo "Copy $fns to $system_scriptpath"
cp $fns $system_scriptpath

echo "Installing piggy to $HOME/.local/bin"
stack install

echo "You might want to put 'source $HOME/.piggy/scripts/funcions'"
echo "in your zshrc If you havn't already done so."
